#!/bin/bash
if [[ ! "$(ls -A $DATA_DIR)" ]]; then
    cp -a /var/.www.orig/. $DATA_DIR 2>/dev/null || :
fi

# Make docker env variables available from within fpm
CONF_FILE=/etc/php5/fpm/pool.d/www.conf
# Function to update the fpm configuration to make the service environment variables available
function setEnvironmentVariable() {

    if [ -z "$2" ]; then
            echo "Environment variable '$1' not set."
            return
    fi

    # Check whether variable already exists
    if grep -q $1 $CONF_FILE; then
        # Reset variable
        sed -i "s/^env\[$1.*/env[$1] = $2/g" $CONF_FILE
    else
        # Add variable
        echo "env[$1] = $2" >> $CONF_FILE
    fi
}

# Clean all docker env variables
sed -i "/^env[.*_PORT_.*]/d" $CONF_FILE

# Grep for variables that look like docker set them (_PORT_)
for _curVar in `env | grep _PORT_ | awk -F = '{print $1}'`;do
    # awk has split them by the equals sign
    # Pass the name and value to our function
    setEnvironmentVariable ${_curVar} ${!_curVar}
done

/usr/sbin/php5-fpm -F >> /var/log/php5-fpm.log 2>&1
